[package]
name = "wgsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

wgpu = { workspace = true, features = ["wgsl"] }
runtime = { workspace = true }
pollster = "0.3.0"
